# Generated by Django 4.2 on 2023-04-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieorder'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_movies',
            field=models.ManyToManyField(related_name='buyers', through='movies.MovieOrder', to='movies.movie'),
        ),
    ]
