# Generated by Django 4.2 on 2023-04-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_rename_added_by_movie_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyed_at', models.DateTimeField(auto_now_add=True)),
                ('buyed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_orders', to=settings.AUTH_USER_MODEL)),
                ('buyed_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_orders', to='movies.movie')),
            ],
        ),
    ]
