# Generated by Django 4.2 on 2023-04-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movieorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieorder',
            name='title',
        ),
    ]
